name: Build and publish multi-arch devcontainer to ghcr.io

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v2
        with:
          use: true

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build devcontainer multi-platform image
        uses: devcontainers/ci@v0.3
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
        with:
          imageName: ghcr.io/mrxcitement/devc-cobol
          cacheFrom: ghcr.io/mrxcitement/devc-cobol
          platform: linux/amd64,linux/arm64
          push: always
